### PR TITLE
Rm initial

### PR DESCRIPTION
**Pull request by rmyers808**
This change is [Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1)

### CODE REVIEW

**Review by jhiga — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1)* status: all files reviewed, 10 unresolved discussions (waiting on @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[setup-aion.py, line 54 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBluZoDIp1oZNeYaGV:-MSBluZoDIp1oZNeYaGW:beq2jpg) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/setup-aion.py#L54)):*
> ```Python
>     parser = argparse.ArgumentParser()
>     parser.add_argument("--aion_url", help="AION URL", type=str,
>                         default="https://spirent.aiontest.net", required=True)
> ```

use `aion.com`

may want to consider adding a subdomain arg
```
parser.add_argument('--subdomain', help='AION subdomain', default='spirent')
parser.add_argument('--aion_url', help='AION URL. In order to insert '
                        'the subdomain automatically, you can specify the url as follows: '
                        'https://{}.spirentaion.com.',
                        default='https://{}.spirentaion.com')
args = parser.parse_args()
if '{}' in args.aion_url:
      args.arion_url = args.aion_url.format(args.subdomain)
```
___
*[setup-aion.py, line 92 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBjQoB0QcSiHf_bKpH:-MSBjQoB0QcSiHf_bKpI:b-wa6tjw) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/setup-aion.py#L92)):*
> ```Python
>     parser.add_argument("--node_storage_remote_uri", help="Node Storage Remote URL", type=str,
>                         default="")
>     
> ```

Please remove whitespace throughout the file.
___
*[setup-aion.py, line 197 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBoA6SDoTuKEDrAFLm:-MSBoA6SDoTuKEDrAFLn:batl7hf) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/setup-aion.py#L197)):*
> ```Python
> 
>     if c["local_addr"]:
>         appUrl = "http://" + c["local_addr"]
> ```

python variables should use underscore.  `app_url` (multiple occurrences in file)
https://www.python.org/dev/peps/pep-0008/#function-and-variable-names
___
*[setup-aion.py, line 200 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBo5sg86gcoFEDk2FK:-MSBo5sg86gcoFEDk2FL:b21nitx) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/setup-aion.py#L200)):*
> ```Python
>     else:       
>         appUrl = "http://" + c["platform_addr"]
>     orionUrl = c["aion_url"]
> ```

orionUrl -> aion_url
___
*[setup-aion.py, line 203 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBo0ao8GInNeAqOktg:-MSBo0ao8GInNeAqOkth:b8feuxp) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/setup-aion.py#L203)):*
> ```Python
> 
>     
>     orgInfo = request(orionUrl + "/api/iam/organizations?subdomain=spirent").json()
> ```

can't assume spirent subdomain
___
*[variables.tf, line 2 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBjaV4CnbGMfg6nxVS:-MSBjaV4CnbGMfg6nxVT:b-h05qsj) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/variables.tf#L2)):*
> ```HCL
> variable "ami" {
>   description = "The AION AMI.  When not specified latests AMI will be used."
> ```

latests -> latest
___
*[variables.tf, line 8 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBjhZwCt1n1yZcqZm6:-MSBjhZwCt1n1yZcqZm7:b-ypkr8p) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/variables.tf#L8)):*
> ```HCL
>   validation {
>     condition     = var.ami == "" || can(regex("^ami-", var.ami))
>     error_message = "Please provide a valid ami id, starting with \"ami-\". or leave blank for latest Windows Server 2019 AMI."
> ```

Windows Server 2019 -> AION
___
*[variables.tf, line 78 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBjxR_22vkYXXTCIIW:-MSBjxR_22vkYXXTCIIX:b-rbxhux) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/variables.tf#L78)):*
> ```HCL
> 
> variable "enable_provisioner" {
>   description = "Enable provisioning"
> ```

Please describe what this means for the user and why they should care about this.
___
*[variables.tf, line 86 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBkN2J-HRqtV3PM9Do:-MSBkN2J-HRqtV3PM9Dp:bq3h1uo) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/variables.tf#L86)):*
> ```HCL
>   description = "AION URL"
>   type        = string
>   default     = "https://spirentaion.com"
> ```

Shouldn't there be a customer domain (e.g. spirent.spirentaion.com)?

We could either add a variable for customer domain so we can default to https://{var.customer}spirentaion.com
or just not have a default but provide an example.
___
*[examples/run-aion/main.tf, line 16 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBlUif2bP_axFzvnMd:-MSBlUig984TkyG_LF_v:b-46qcon) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/examples/run-aion/main.tf#L16)):*
> ```HCL
> 
>   subnet_id           = "subnet-ffe75cb2"
>   ingress_cidr_blocks = ["74.87.49.203/32"]
> ```

Hide actual values in the example.

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1)* status: 6 of 10 files reviewed, 10 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @radhikabhat08)

___
*[setup-aion.py, line 54 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBluZoDIp1oZNeYaGV:-MSDLL0uDgrsOyGMjyW6:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/setup-aion.py#L54)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

use `aion.com`

may want to consider adding a subdomain arg
```
parser.add_argument('--subdomain', help='AION subdomain', default='spirent')
parser.add_argument('--aion_url', help='AION URL. In order to insert '
                        'the subdomain automatically, you can specify the url as follows: '
                        'https://{}.spirentaion.com.',
                        default='https://{}.spirentaion.com')
args = parser.parse_args()
if '{}' in args.aion_url:
      args.arion_url = args.aion_url.format(args.subdomain)
```
</blockquote></details>

Done.
___
*[setup-aion.py, line 92 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBjQoB0QcSiHf_bKpH:-MSDLMMt1OPSwsNj6epS:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/setup-aion.py#L92)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Please remove whitespace throughout the file.
</blockquote></details>

Done.
___
*[setup-aion.py, line 197 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBoA6SDoTuKEDrAFLm:-MSDLS8d0GF-HlcqMtgK:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/setup-aion.py#L197)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

python variables should use underscore.  `app_url` (multiple occurrences in file)
https://www.python.org/dev/peps/pep-0008/#function-and-variable-names
</blockquote></details>

Done.
___
*[setup-aion.py, line 200 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBo5sg86gcoFEDk2FK:-MSDLTMdCvRsxBNd6Kl_:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/setup-aion.py#L200)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

orionUrl -> aion_url
</blockquote></details>

Done.
___
*[setup-aion.py, line 203 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBo0ao8GInNeAqOktg:-MSDLc8N0MwAMYJepQwR:b1bgh32) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/setup-aion.py#L203)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

can't assume spirent subdomain
</blockquote></details>

Fixed by using default.  This works because  company name is in the URL.
___
*[variables.tf, line 2 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBjaV4CnbGMfg6nxVS:-MSDLxjrEmbAjdQ2D17r:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/variables.tf#L2)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

latests -> latest
</blockquote></details>

Done.
___
*[variables.tf, line 8 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBjhZwCt1n1yZcqZm6:-MSDLzCF25STqk0LbwO2:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/variables.tf#L8)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Windows Server 2019 -> AION
</blockquote></details>

Done.
___
*[variables.tf, line 78 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBjxR_22vkYXXTCIIW:-MSDM01u7556VmPmIaB1:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/variables.tf#L78)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Please describe what this means for the user and why they should care about this.
</blockquote></details>

Done.
___
*[variables.tf, line 86 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBkN2J-HRqtV3PM9Do:-MSDM1EG4vLTb7QGmyXE:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/variables.tf#L86)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Shouldn't there be a customer domain (e.g. spirent.spirentaion.com)?

We could either add a variable for customer domain so we can default to https://{var.customer}spirentaion.com
or just not have a default but provide an example.
</blockquote></details>

Done.
___
*[examples/run-aion/main.tf, line 16 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBlUif2bP_axFzvnMd:-MSDM97tC6xGE3YkFZ6a:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/examples/run-aion/main.tf#L16)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Hide actual values in the example.
</blockquote></details>

Done.

**Review by jhiga — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1)* status: all files reviewed, 4 unresolved discussions (waiting on @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[setup-aion.py, line 92 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBjQoB0QcSiHf_bKpH:-MSEav7YDOGnWInde22q:b-uvxwbv) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/setup-aion.py#L92)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still see unnecessary leading and trailing whitespace (e.g. look 6 lines down).
___
*[setup-aion.py, line 200 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBo5sg86gcoFEDk2FK:-MSEd6XU5sdi3vTo6YAr:ba4eo9b) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/setup-aion.py#L200)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

please change to `aion_url`
___
*[setup-aion.py, line 260 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSEbuSQ13MX_pA2GHfs:-MSEbuSQ13MX_pA2GHft:bm5lczw) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/932429fd78229542d60fbf9a3aff410764008850/setup-aion.py#L260)):*
> ```Python
>                 
>             if (time.time() - start_time) > wait_time:
>                 LOG.warning("platform initialized didn't complete in %d seconds. platform wait timed out." % wait_time)
> ```

initialized -> initialization
___
*[setup-aion.py, line 265 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSEbq2N-ABoGDvH-9W6:-MSEbq2N-ABoGDvH-9W7:b-3v8v2a) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/932429fd78229542d60fbf9a3aff410764008850/setup-aion.py#L265)):*
> ```Python
> 
>     if not completed:
>         raise Exception("platform initialized did not complete")
> ```

initialized -> initialization

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @radhikabhat08)

___
*[setup-aion.py, line 92 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSBjQoB0QcSiHf_bKpH:-MSFGPgeC7bCuWXDD1qv:b-ti241s) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/b3de77f9ad399553b491fae34f5e3efaa8622dff/setup-aion.py#L92)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Still see unnecessary leading and trailing whitespace (e.g. look 6 lines down).
</blockquote></details>

Fixed and ran pycodestyle
___
*[setup-aion.py, line 260 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSEbuSQ13MX_pA2GHfs:-MSFGpSl6wyCECoep2g5:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/932429fd78229542d60fbf9a3aff410764008850/setup-aion.py#L260)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

initialized -> initialization
</blockquote></details>

Done.
___
*[setup-aion.py, line 265 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSEbq2N-ABoGDvH-9W6:-MSFGv6H4k2R4PrHiAo3:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/932429fd78229542d60fbf9a3aff410764008850/setup-aion.py#L265)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

initialized -> initialization
</blockquote></details>

Done.

**Review by jhiga — APPROVED** [review]
:lgtm: after fixing typos

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-:-MSGdIw96NGzjggHpHn9:b-flwo41)* status: all files reviewed, 3 unresolved discussions (waiting on @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[README.md, line 10 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSGcQzf6ymwdkS3lfjE:-MSGcQzf6ymwdkS3lfjF:b9vil8h) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/be01d890e825d95cb8515d9d9fcf915acb6a97b2/README.md#L10)):*
> ```Markdown
> If you would like to configure the Spirent AION platform in a web browser set the variable enable_provisioner=false.  Otherwise when enable_provisioner=true the instance will be configured however license entitlement & product installation should be completed in your web browser (see below).
> 
> ### Add Licesnse Entitlements
> ```

Licesnse -> License
___
*[README.md, line 14 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSGcY-T20xL69Gk0udS:-MSGcY-T20xL69Gk0udT:bixymbr) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/be01d890e825d95cb8515d9d9fcf915acb6a97b2/README.md#L14)):*
> ```Markdown
> 2. Click on "Install Entitlements"
> 3. Use one of the following methods to add entitlements (#1 is prefered)
>    1. Login to spirentaion.com and selet entitlements to host in the new instance
> ```

spirentaion.com -> <your_org>.spirentaion.com

selet -> seclect
___
*[README.md, line 16 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSGcm-i00usopsgMelS:-MSGcm-i00usopsgMelT:bldffse) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/be01d890e825d95cb8515d9d9fcf915acb6a97b2/README.md#L16)):*
> ```Markdown
>    1. Login to spirentaion.com and selet entitlements to host in the new instance
>       Note: Hosted entitlements should be released before destroying the instance.  When entitlements are not released you will need to contact Spirent support to release them for you.
>    2. Install a license enttitlement file obtained from Spirent support
> ```

enttitlement -> entitlement

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @radhikabhat08)

___
*[README.md, line 10 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSGcQzf6ymwdkS3lfjE:-MSTsXDk-pkPstUY79QA:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/be01d890e825d95cb8515d9d9fcf915acb6a97b2/README.md#L10)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Licesnse -> License
</blockquote></details>

Done.
___
*[README.md, line 14 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSGcY-T20xL69Gk0udS:-MSTs_8BDv_MXq-7ft_C:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/be01d890e825d95cb8515d9d9fcf915acb6a97b2/README.md#L14)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

spirentaion.com -> <your_org>.spirentaion.com

selet -> seclect
</blockquote></details>

Done.
___
*[README.md, line 16 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-aion/1#-MSGcm-i00usopsgMelS:-MSTsa6-2KJa5eBgoCRA:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-aion/blob/be01d890e825d95cb8515d9d9fcf915acb6a97b2/README.md#L16)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

enttitlement -> entitlement
</blockquote></details>

Done.

**Pull request merged**
